### ISSUE TITLE
При выборе улицы ошибка вылетает

### ISSUE THREAD

**Issue by ustnv** [tadata-ru/dtp-stat#10]
Заметил, что не работает фильтр по улицам.

**Comment by xeningem** [comment]
Не могу воспроизвести. Можно какой-то пример конкретный?

**Comment by ustnv** [comment]
Мне с хабра писали, у меня получалось воспроизвести, но я забыл точно как. Сейчас не получается)


![](https://habrastorage.org/webt/id/sp/19/idsp19rod4k5cqmf-8ajii7sd4u.png)

**Comment by ustnv** [comment]
Вроде не подтвердилось, больше не воспроизводится
