### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by kazhuravlev** [tadata-ru/dtp-stat#16]
For deployment in simple (single instance) mode project may have a Dockerfile or another tool. 

I think, that Docker is good choice, because Docker is very popular and give a lowers entry threshold.

**Comment by approximatenumber** [comment]
already trying to dockerize this application. One contatiner may be not right, because there are 3 different substances: database, node-part and django-part. So I think docker-service is a better choice.

**Comment by approximatenumber** [comment]
PR #29 resolved it
