### ISSUE TITLE
г. Сочи - неверная геопозиция многих ДТП (в море, за границей)

### ISSUE THREAD

**Issue by bender-spb** [tadata-ru/dtp-stat#18]
Для г. Сочи многие ДТП неверно отображаются в Черном море или за границей РФ 
https://dtp-stat.ru/krasnodarskii-krai_sochi/

![image](https://user-images.githubusercontent.com/9783949/52273250-f1f58500-2951-11e9-9abf-1a771b8dc5f6.png)

![image](https://user-images.githubusercontent.com/9783949/52273169-b5298e00-2951-11e9-90e1-ec233b4f2ef2.png)

Можно попробовать рассмотреть эту проблему системно и в рамках проверки качества данных автоматически находить ДТП за границами выбранной области (города, в данном случае) и ДТП которые отображаются "на воде"

**Comment by bender-spb** [comment]
Видно что есть некая системная ошибка (линия ДТП в море идущая вдоль побережья). Возможно причина в следующем:

изначально координаты были записаны в формате градусы, минуты и секунды: 
43°40'10"  39°37'28"

однако в базе ГИБДД они хранятся (без должного преобразования) в виде десятичной дроби градусов : 
43.4010  39.3728

На примере ДТП [177173280](https://dtp-stat.ru/dtp/177173280):
Координаты из базы: [43.4010 39.3728](https://www.google.ru/maps/place/43%C2%B024'03.6%22N+39%C2%B022'22.1%22E/@43.5640855,39.3412068,9.89z/data=!4m5!3m4!1s0x0:0x0!8m2!3d43.401!4d39.3728)
Координаты какими они должны быть: [43°40'10"  39°37'28"](https://www.google.ru/maps/place/43%C2%B040'10.0%22N+39%C2%B037'28.0%22E/@43.6694444,39.6222557,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d43.6694444!4d39.6244444)
Это довольно точно соответствует указаной точке в карточке ДТП: 160,6км трассы А-147:
https://multigo.ru/trassa/A147?km=160
https://multigo.ru/trassa/A147?km=161

**Comment by ustnv** [comment]
Спасибо за разбор, есть идеи как такие координаты выискивать среди всех?

**Comment by bender-spb** [comment]
К сожалению, пока не вижу способа легко и достоверно идентифицировать их алгоритмически.

Варианты, в какую сторону можно копать:
1. Мы можем точно не подозревать такую ошибку если координаты очевидно записаны как десятичная дробь. А именно 45.**X**5**Y**7 когда X или Y =6, 7, 8, 9
2. Кажется, что для каждого конкретного города можно найти функцию (например, прямую на карте) отделяющую "ложные" координаты от не ложных. Имея на руках это уравнение можно алгоритмически выделить такие ложные координаты для конкретного города:
![image](https://user-images.githubusercontent.com/9783949/52478078-e4880700-2bac-11e9-8e68-3a401949a6f6.png)

**Comment by bender-spb** [comment]
В итоге на данном этапе мне кажется полезным добавить фичу "Отметить координаты ДТП как возможно неверное". 
Что бы в дальнейшем массово работать с такими ДТП. 

Пример 1: пользователь в UI видит что ДТП явно в неправильном месте и "отмечает" его. Возможно будет полезно так же ввести/хранить "преполагаемые актуальные координаты" (которые часто ясны по адресу или километру трассы) 

Пример 2: пишем и запускаем скрипт который как-то определяет "возможно неверные" координаты ДТП и помечает такие ДТП в БД для дальнейшего разбора.

**Comment by ustnv** [comment]
Закрываю эту задачу, можно продолжить обсуждение тут - https://github.com/tadata-ru/dtp-stat/issues/6
