### ISSUE TITLE
Карта зависает при скроллинге с тепловым слоем

### ISSUE THREAD

**Issue by ustnv** [tadata-ru/dtp-stat#3]
При активном скроллинге по карте, отдалении и приближении в какой-то момент начинает зависать карта и появляются ошибки `Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`.

**Comment by ierodistinlpk** [comment]
Firefox Quantum 60.4.0esr (32-бит) при попытке воспроизвести появляются ошибки.
ошибка из первого сообщения не появилась.
`InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
main-7de4642c2b74309db1b0.js:17
_drawAlpha
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:144824
renderAll
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:143342
on/<
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:146221
emit
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:146317
setData
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:141368
setData
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:147236
_update
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:22:17603
_draw
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:22:17035
_reset
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:22:18669
fire
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:4923
_moveEnd
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:38640
_onZoomTransitionEnd/<
https://dtp-stat.ru/static/bundles/main-7de4642c2b74309db1b0.js:17:45353
<анонимная> self-hosted:976:17 `

**Comment by xeningem** [comment]
Воспроизводится ли ещё?

**Comment by c13** [comment]
Воспроизводится в Chrome 71 при масштабировании колесиком мышки (несколько раз)
![image](https://user-images.githubusercontent.com/1741510/52591920-32736800-2e56-11e9-81fa-1c8cc9085665.png)

**Comment by xeningem** [comment]
> Воспроизводится в Chrome 71 при масштабировании колесиком мышки (несколько раз)
> ![image](https://user-images.githubusercontent.com/1741510/52591920-32736800-2e56-11e9-81fa-1c8cc9085665.png)

Это старая версия - видишь, на карте нет кнопки геолокация. Воспроизводится ли у тебя на текущей? (не забудь кеш почистить)

**Comment by c13** [comment]
Сейчас нет.
В консоль пишутся события такого вида, но это не так страшно
`e {cfg: {…}, _el: div.leaflet-zoom-hide, _data: Array(8200), _max: 2, _min: 0, …}
cfg: {scaleRadius: true, radius: 0.001, minOpacity: 0.1, max_val: 1, gradient: {…}, …}
_data: (8200) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]
_el: div.leaflet-zoom-hide
_heatmap: a {_config: {…}, _coordinator: t, _renderer: n, _store: e}
_height: 996
_initHooksCalled: true
_leaflet_id: 8313
_map: e {options: {…}, _handlers: Array(6), _layers: {…}, _zoomBoundLayers: {…}, _sizeChanged: false, …}
_mapToAdd: e {options: {…}, _handlers: Array(6), _layers: {…}, _zoomBoundLayers: {…}, _sizeChanged: false, …}
_max: 2
_min: 0
_origin: j {lat: 56.024866728290874, lng: 37.03765869140626}
_width: 1118
_zoomAnimated: true
__proto__: e`
