### ISSUE TITLE
Нет тестов

### ISSUE THREAD

**Issue by ustnv** [tadata-ru/dtp-stat#4]
У нас вообще нет тестов. Давайте их сделаем.

**Comment by c13** [comment]
Нужно несколько тестов для парсера и несколько для самого сайта
Желательно обернуть их в систему автосборки circleci или travisci.

**Comment by approximatenumber** [comment]
Предлагаю начать с #42

**Comment by approximatenumber** [comment]
Предлагаю закрыть, как не вполне описанную проблему, которая частично решена. В дальнейшем открывать тикеты более конкретные
